### ISSUE TITLE
server-side FirstBoutPlanningTime bug

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#266]
The server outputs this error when no User is logged in.

```
server_1    | 23:32:45 dev.1  | [05/Aug/2021 23:32:45] "GET /api/fitbit/account HTTP/1.1" 404 2
server_1    | 23:32:45 dev.1  | Internal Server Error: /api/first-bout-planning-time
server_1    | 23:32:45 dev.1  | Traceback (most recent call last):
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
server_1    | 23:32:45 dev.1  |     response = get_response(request)
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
server_1    | 23:32:45 dev.1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server_1    | 23:32:45 dev.1  |     return view_func(*args, **kwargs)
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
server_1    | 23:32:45 dev.1  |     return self.dispatch(request, *args, **kwargs)
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
server_1    | 23:32:45 dev.1  |     response = self.handle_exception(exc)
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
server_1    | 23:32:45 dev.1  |     self.raise_uncaught_exception(exc)
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
server_1    | 23:32:45 dev.1  |     raise exc
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
server_1    | 23:32:45 dev.1  |     response = handler(request, *args, **kwargs)
server_1    | 23:32:45 dev.1  |   File "/server/bout_planning_notification/views.py", line 30, in get
server_1    | 23:32:45 dev.1  |     if serialized.is_valid():
server_1    | 23:32:45 dev.1  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in is_valid
server_1    | 23:32:45 dev.1  |     'Cannot call `.is_valid()` as no `data=` keyword argument was '
server_1    | 23:32:45 dev.1  | AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
```

**[To close this issue, you need to satisfy all of these:]**
- [ ] fix the error

**Comment by jup014** [comment]
fixed by https://github.com/kpwhri/heartsteps/commit/b8996ed3899f7734a780379e0fdb669f01a57891
